# The URL the site will be built for
base_url = "https://nav.ccnu.link"
title = "懒人导航"
compile_sass = true
build_search_index = false
default_language = "zh"
minify_html = true

[markdown]
highlight_code = false

[extra]
# Put all your custom variables here
